kind: pipeline
type: docker
name: default

trigger:
  event:
    - push
    - custom
  branch:
    - main

steps:
  - name: build-and-push-web
    image: plugins/docker
    settings:
      registry: "${REGISTRY_HOST}:${REGISTRY_PORT}"
      repo:     "${REGISTRY_HOST}:${REGISTRY_PORT}/rimtes-web"
      context:  .
      dockerfile: dockerfile
      tags:
        - "${DRONE_COMMIT_SHA}"
        - latest

  - name: build-and-push-smtp
    image: plugins/docker
    settings:
      registry: "${REGISTRY_HOST}:${REGISTRY_PORT}"
      repo:     "${REGISTRY_HOST}:${REGISTRY_PORT}/rimtes-smtp"
      context:  smtp
      dockerfile: dockerfile
      tags:
        - "${DRONE_COMMIT_SHA}"
        - latest

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: "${SSH_HOST}"
      port: "${SSH_PORT}"
      user: root
      key:
        from_secret: SSH_DEPLOY_KEY
    environment:
      EMAIL_USER:
        from_secret: EMAIL_USER
      EMAIL_PASS:
        from_secret: EMAIL_PASS
    script:
      - cd /mnt/user/appdata/rimtes
      - echo "EMAIL_USER=${EMAIL_USER}" > .env
      - echo "EMAIL_PASS=${EMAIL_PASS}" >> .env
      - docker-compose pull
      - docker-compose up -d --build
