kind: pipeline
type: docker
name: default

trigger:
  event:
    - push
    - custom
  branch:
    - main

steps:
  - name: build-and-push-web
    image: plugins/docker
    environment:
      REGISTRY_HOST:
        from_secret: REGISTRY_HOST
    settings:
      registry: ${REGISTRY_HOST}
      repo: ${REGISTRY_HOST}/rimtes-web
      tags:
        - ${DRONE_COMMIT_SHA}
        - latest

  - name: build-and-push-smtp
    image: plugins/docker
    environment:
      REGISTRY_HOST:
        from_secret: REGISTRY_HOST
    settings:
      registry: ${REGISTRY_HOST}
      repo: ${REGISTRY_HOST}/rimtes-smtp
      tags:
        - ${DRONE_COMMIT_SHA}
        - latest

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: SSH_HOST
      user: root
      port: 22
      key:
        from_secret: SSH_DEPLOY_KEY
    environment:
      EMAIL_USER:
        from_secret: EMAIL_USER
      EMAIL_PASS:
        from_secret: EMAIL_PASS
    script:
      - cd /mnt/user/appdata/rimtes
      - echo "EMAIL_USER=${EMAIL_USER}" > .env
      - echo "EMAIL_PASS=${EMAIL_PASS}" >> .env
      - docker-compose pull
      - docker-compose up -d --build
