kind: pipeline
type: docker
name: default

############################################################
# Trigger
############################################################
trigger:
  event:
    - push
    - custom
  branch:
    - main

############################################################
# Step 1 – Build + push Angular web image
############################################################
steps:
- name: build-and-push-web
  image: plugins/docker
  settings:
    registry: 192.168.50.200:5000
    repo:     192.168.50.200:5000/rimtes-web
    insecure: true
    context:  .
    dockerfile: dockerfile
    tags:
      - ${DRONE_COMMIT_SHA}
      - latest

############################################################
# Step 2 – Build + push SMTP image
############################################################
- name: build-and-push-smtp
  image: plugins/docker
  settings:
    registry: 192.168.50.200:5000
    repo:     192.168.50.200:5000/rimtes-smtp
    insecure: true
    context:  smtp
    dockerfile: smtp/dockerfile
    tags:
      - ${DRONE_COMMIT_SHA}
      - latest

############################################################
# Step 3 – Deploy to Un-raid via SSH
############################################################
- name: deploy
  image: appleboy/drone-ssh

  # ▸ secrets that must be expanded inside the script
  environment:
    EMAIL_USER:
      from_secret: EMAIL_USER
    EMAIL_PASS:
      from_secret: EMAIL_PASS

  # ▸ SSH connection + remote commands
  settings:
    host:
      from_secret: SSH_HOST
    port:
      from_secret: SSH_PORT
    username: root
    key:
      from_secret: SSH_DEPLOY_KEY

    script:
      - set -ex                                      # echo commands, fail fast
      # pull images just built by previous steps
      - docker pull 192.168.50.200:5000/rimtes-web:${DRONE_COMMIT_SHA}
      - docker pull 192.168.50.200:5000/rimtes-smtp:${DRONE_COMMIT_SHA}

      # remove old containers if present
      - docker rm -f rimtes-web rimtes-smtp || true

      # start new versions
      - docker run -d --name rimtes-web \
          --restart=always              \
          -p 3004:80                    \
          192.168.50.200:5000/rimtes-web:${DRONE_COMMIT_SHA}

      - docker run -d --name rimtes-smtp \
          --restart=always              \
          -p 3005:3000                  \
          -e EMAIL_USER=${EMAIL_USER}   \
          -e EMAIL_PASS=${EMAIL_PASS}   \
          192.168.50.200:5000/rimtes-smtp:${DRONE_COMMIT_SHA}

      # show status in Drone log
      - docker ps --filter name=rimtes --format '{{.Names}}\t{{.Status}}\t{{.Ports}}'

  # ▸ make sure this step waits for both image-build steps
  depends_on:
    - build-and-push-web
    - build-and-push-smtp
