version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    image: 192.168.50.200:5000/rimtes-web:latest
    ports:
      - "80:80"
    restart: always

  smtp:
    build:
      context: ./smtp
      dockerfile: smtp/dockerfile
    image: 192.168.50.200:5000/rimtes-smtp:latest
    ports:
      - "3000:3000"
    environment:
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    restart: always
